spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
#  jpa:
#    show-sql: true
#  flyway:
#    enabled: false #
  h2:
    console:
      enabled: true
#logging:
#  level:
#    root: WARN
